[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "Pioneers Docs"
authors = [{name = "Otto", email = "grentomato@gmail.com"}]
dynamic = ["version", "description"]
